### ISSUE TITLE
Add new template for PMPro Drip Series Add On

### ISSUE THREAD

**Issue by eviolini** [strangerstudios/pmpro-email-templates#22]
In the [PMPro Drip Series Add On](https://www.paidmembershipspro.com/add-ons/pmpro-series-for-drip-feed-content/), the email that is sent to users when new content is added is not available to edit from the Paid Memberships Pro Email Template Add On. This template should be added for customizations.

**Comment by kimcoleman** [comment]
This would be an issue/update needed in the Series Add On. The Email Templates Admin Editor uses a filter to include emails and doesn't specifically support an Add On's email (the Add On supports it).

There is a PR for this feature here: https://github.com/strangerstudios/pmpro-series/pull/47
