### ISSUE TITLE
Undefined Constant When PMPro Core is Deactivated

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/pmpro-email-templates#52]
The `PMPRO_VERSION` is undefined when PMPro Core is deactivated.

Exact error: `Use of undefined constant PMPRO_VERSION - assumed 'PMPRO_VERSION' (this will throw an Error in a future version of PHP)`

https://github.com/strangerstudios/pmpro-email-templates/blob/dev/includes/init.php#L171

Can be resolved by adding a `defined` check.

**Comment by michaelbeil** [comment]
A [customer sent in a ticket (**moderators only**)](https://www.paidmembershipspro.com/forums/topic/update-issue/) and another [customer sent in a different ticket (**moderators only**)](https://www.paidmembershipspro.com/forums/topic/errors-after-upgrading-to-v2-5/) running into this error:
>Warning: Use of undefined constant PMPRO_VERSION – assumed ‘PMPRO_VERSION’ (this will throw an Error in a future version of PHP) in .../public_html/wp-content/plugins/pmpro-email-templates-addon/includes/init.php on line 171 Warning: Cannot modify header information – headers already sent by (output started at .../public_html/wp-content/plugins/pmpro-email-templates-addon/includes/init.php:171) in /.../public_html/wp-includes/functions.php on line 6274

**Comment by michaelbeil** [comment]
Another [customer sent in a ticket (**moderators only**)](https://www.paidmembershipspro.com/forums/topic/error-msgs-after-2-5-4-upgrade/) experiencing this error.
